agents:
  queue: hosted

steps:
  - label: ":shell: Shellcheck"
    key: shellcheck
    plugins:
      shellcheck#v1.4.0:
        files:
          - hooks/**
          - lib/**
          - commands/**

  - label: ":sparkles: Lint"
    key: lint
    plugins:
      plugin-linter#v3.3.0:
        id: monorepo-diff

  - label: ":golang: Test"
    key: test
    command: go test ./...
    plugins:
      - docker#v5.14.0:
          image: "golang"
          always-pull: true
          workdir: /plugin
          mount-buildkite-agent: true

  - label: ":linux: Build"
    key: build
    command: make local
    artifact_paths: monorepo-diff-buildkite-plugin
    plugins:
      - docker#v5.14.0:
          image: "golang"
          always-pull: true
          workdir: /plugin

  - wait: ~
    depends_on:
      - shellcheck
      - lint
      - test
      - build

  - label: ":rocket: :github: Release"
    key: release
    artifact_paths:
      - dist/**/*
    secrets:
      - GITHUB_TOKEN
    plugins:
      - docker#v5.14.0:
          image: "goreleaser/goreleaser:v2.17.1"
          always-pull: true
          workdir: /plugin
          environment:
            - GITHUB_TOKEN
          command:
            - release
            - --clean
